# -*- coding: utf-8 -*-
#
# Brain Modeling Toolkit documentation build configuration file, created by
# sphinx-quickstart on Tue Sep 26 10:33:33 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import glob
import shutil
from pathlib import Path


sys.path.insert(0, os.path.abspath('../../..'))
import bmtk


conf_path = Path(__file__).parent.resolve()


# Location of where document "sources" are found. By default should be in the same path 
# as the conf.py file.
docs_source_path = conf_path

# A list of jupyter notebook (ipynb) paths that that will be imported into the source folder
# and converted to html. If you want to add a notebook tutorial that will show up in the bmtk 
# documentation make sure it can be found in one of the path's below:
# NOTE:
#  - Avoid absolute paths or paths outside the bmtk repo, otherwise other people may not be able to 
#    to fully rebuild documentation.
#  - All notebooks will be copied to the "docs/autodocs/source/tutorials/" folder, so make sure 
#    filenames are unique.
notebook_paths = [
    conf_path / '../../tutorial/*.ipynb',
    conf_path / '../../tutorial/**/*.ipynb'
]


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.githubpages',
    'sphinx.ext.viewcode',
    'numpydoc',
    'sphinx.ext.autosummary',
    'nbsphinx',
    'IPython.sphinxext.ipython_console_highlighting',
    'sphinx_design'
]

# Add any paths that contain templates here, relative to this directory.
# templates_path = ['_templates', 'aibs_sphinx/templates']
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = ['.rst', '.ipynb']

autodoc_mock_imports = ['nest', 'lxml', 'bluepyopt', 'utils']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Brain Modeling Toolkit'
copyright = u'2021, Allen Institute for Brain Science'
author = u'Allen Institute for Brain Science'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = bmtk.__version__
# The full version, including alpha/beta/rc tags.
release = bmtk.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


numpydoc_show_class_members = False

nbsphinx_allow_errors = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_css_files = [
    'custom.css',
]
html_theme_path = ['.']
# html_theme = 'aibs_sphinx'
# html_theme = 'alabaster'
html_theme = 'pydata_sphinx_theme'
html_logo = "_static/images/allen-logo.svg"
html_theme_options = {
    "show_prev_next": False,             # Do not show the prev & next buttons at the bottom of the page
    "header_links_before_dropdown": 8,   # By default pyshinx will only show 5 items in navbar then a "more" dropdown. Increase num of items to show all top pages
    "logo": {
        "link": "https://alleninstitute.org/",
    }
}


html_sidebars = {
    # '**': ["sbt-sidebar-nav.html"]
    # '**': ['custom_sidebar.html', 'localtoc.html', 'searchbox.html'],
    # '**': ['user_guide'],
    # "simulators_guide": ["user_guide.html"],
    "news_and_events": [],
    "contact_us": [],
    "how_to_cite": [],
    # "installation": [],
}

# html_sidebars = {
#     '**': [
#         'globaltoc.html',
#         # 'searchbox.html'
#     ],
# }

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static', 'aibs_sphinx/static']
html_static_path = ['_static']
html_extra_path = ['../.nojekyll']
# html_theme_options = {
#     # "sidebarwidth": "300",
#     "navbar_align": "left",
# }

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     # '**': [
#     #     'globaltoc.html',
#     #     'searchbox.html'
#     # ],
#     # "simulators_guide": []
# }




# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'BrainModelingToolkitdoc'

html_show_sphinx = False
html_show_copyright = False


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'BrainModelingToolkit.tex', u'Brain Modeling Toolkit Documentation',
     u'Kael Dai', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'brainmodelingtoolkit', u'Brain Modeling Toolkit Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'BrainModelingToolkit', u'Brain Modeling Toolkit Documentation',
     author, 'BrainModelingToolkit', 'One line description of project.',
     'Miscellaneous'),
]


def copy_tutorials(ipynb_dest='tutorials', static_dest='_static'):
    """ In order for nbsphinx to convert .ipynb tutorials into html they must be first copied into 
    the autodocs/source/ directory, along with any embedded images and associated files. 
    """
    # Create a folder to move all the jupyter-notebooks and images to.   
    if not Path(ipynb_dest).is_absolute():
        ipynb_dest = docs_source_path / ipynb_dest

    if not Path(static_dest).is_absolute():
        static_dest = ipynb_dest / static_dest

    Path(ipynb_dest).mkdir(parents=True, exist_ok=True)
    Path(static_dest).mkdir(parents=True, exist_ok=True)

    notebook_folders = set()
    for nbpath in notebook_paths:
        nbpath = nbpath.as_posix() if isinstance(nbpath, Path) else nbpath
        for ipynb_path in glob.glob(nbpath):
            notebook_folders.add(Path(ipynb_path).parent.resolve())
            shutil.copy(ipynb_path, ipynb_dest)

    for nbfolder in notebook_folders:
        static_subfolder = nbfolder / '_static'
        if static_subfolder.exists():
            shutil.copytree(static_subfolder, static_dest, dirs_exist_ok=True)


def copy_tutorials_old():
    """In order for nbsphinx to convert .ipynb tutorials into html they must be first copied into 
    the autodocs/source/ directory, along with any embedded images and associated files. 
    """
    autodocs_src_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Get path of original .ipynb files
    
    tut_src_dir = os.path.abspath('../tutorial')
    tutorials = os.path.join(tut_src_dir, '**/*.ipynb')


    # Path to where .ipynb file will be moved to. To make things easier to manage any jupyter notebooks
    # imported will be placed in a separate tutorials/ direction that must be created on first use.
    tut_dest_dir = os.path.join(autodocs_src_dir, 'tutorials')
    if not os.path.exists(tut_dest_dir):
        os.makedirs(tut_dest_dir)   

    # Copy each ipynb file from ../tutorial/ to ./source/tutorials/
    for ipynb_file in glob.glob(tutorials):
        tut_fname = os.path.basename(ipynb_file)
        # if tut_fname.startswith('00') or tut_fname.startswith('tutorial_introduction') \
        #         or tut_fname.startswith('Simulation_Intro'):
        #     continue
        if tut_fname[:2].isnumeric():
            tut_fname = tut_fname[3:]

        print(ipynb_file)

        tut_dest_path = os.path.join(tut_dest_dir, tut_fname)
        shutil.copy(ipynb_file, tut_dest_path)

    # Copy tutorial images into ./source directory
    images_src_dir = os.path.join(tut_src_dir, '_static/_tutorial_images')
    images_dest_dir = os.path.join(tut_dest_dir, '_static/_tutorial_images')
    if os.path.exists(images_dest_dir):
        shutil.rmtree(images_dest_dir)

    shutil.copytree(images_src_dir, images_dest_dir)


def autodoc_skip_member(app, what, name, obj, skip, options):
    return skip or name in ['load_reports', 'plot_report', 'bmtk.analyzer.cell_vars']


def setup(app):
    copy_tutorials()
    app.connect('autodoc-skip-member', autodoc_skip_member)
